---
name: CI

on:
    push:
        branches:
            - development
            - stable
    pull_request:
    schedule:
        - cron: 0 0 * * 0 # weekly

jobs:
    bazel_test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python: [3.9]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install build dependencies
              uses: ./.github/actions/install-build-dependencies

            - name: Test
              run: make test
              env:
                  CC: clang
                  CXX: clang++
                  BAZEL_OPTS: --batch
                  BAZEL_TEST_OPTS: --config=ci --test_timeout=300,900,1800,7200

    install_test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python: [3.6, 3.7, 3.8, 3.9]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install build dependencies
              uses: ./.github/actions/install-build-dependencies

            - name: Install
              run: make install
              env:
                  CC: clang
                  CXX: clang++
                  BAZEL_OPTS: --batch
                  BAZEL_BUILD_OPTS: --config=ci

            - name: Test
              run: make install-test
              env:
                  CC: clang
                  CXX: clang++

            - name: Uninstall
              run: make purge
