---
# This file defines a GitHub actions job that runs the fuzzing test suite for
# 10 minutes every weekday against the latest CompilerGym release. The job can
# also be scheduled manually using the GitHub actions UI.
#
# TODO(cummins): Set up https://github.com/JasonEtco/create-an-issue
# to create a boilerplate issue if `make fuzz` fails.
name: Release Fuzz

on:
    workflow_dispatch:
    schedule:
        - cron: 0 9 * * 1-5  # every weekday at 9am

jobs:
    fuzz:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python: [3.9]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install build dependencies
              uses: ./.github/actions/install-build-dependencies

            - name: Install
              run: make install
              env:
                  CC: clang
                  CXX: clang++
                  BAZEL_OPTS: --batch
                  BAZEL_TEST_OPTS: --config=ci

            - name: Test
              run: FUZZ_TIME=600 make install-fuzz
