---
name: Release Test

on:
    workflow_dispatch:
    schedule:
        - cron: 0 0 * * 0 # weekly

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python: [3.6, 3.7, 3.8, 3.9]

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: stable

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install runtime dependencies (macos)
              run: brew install zlib
              if: matrix.os == 'macos-latest'

            - name: Install python wheel
              run: python -m pip install compiler_gym
              env:
                  LDFLAGS: -L/usr/local/opt/zlib/lib
                  CPPFLAGS: -I/usr/local/opt/zlib/include
                  PKG_CONFIG_PATH: /usr/local/opt/zlib/lib/pkgconfig

            - name: Install python test dependencies
              run: python -m pip install -r tests/requirements.txt

            - name: Test
              run: make install-test
              env:
                  CC: clang
                  CXX: clang++
